service: AWS-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:407236388192:table/userTable

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get

  createtask:
    handler: src/add.addtask
    events:
      - httpApi:
          path: /task
          method: post

  gettasks:
    handler: src/gettasks.gettasks
    events:
      - httpApi:
          path: /tasks
          method: get

  gettask:
    handler: src/gettask.gettask
    events:
      - httpApi:
          path: /task/{id}
          method: get

  updatetask:
    handler: src/updatetask.updatetask
    events:
      - httpApi:
          path: /task/{id}
          method: put

  deletetask:
    handler: src/deletetask.deletetask
    events:
      - httpApi:
          path: /task/{id}
          method: delete

resources: # CloudFormation template syntax
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

